// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDbl8o7ZRowpiHNBG0WoIqevrciS37Os',
    appId: '1:86845493759:web:c97c0182aa23d62cad97ca',
    messagingSenderId: '86845493759',
    projectId: 'meninki-903d5',
    authDomain: 'meninki-903d5.firebaseapp.com',
    storageBucket: 'meninki-903d5.firebasestorage.app',
    measurementId: 'G-19Z3X1KLDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3WNTXYZg5Vhvahh37SbDCIcyYoxVOhk',
    appId: '1:86845493759:android:b3668d09f1353a55ad97ca',
    messagingSenderId: '86845493759',
    projectId: 'meninki-903d5',
    storageBucket: 'meninki-903d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMorEvIYf8OfbdBCEqZqUVdpzHtua7lwM',
    appId: '1:86845493759:ios:4a8d2fd9f2728bf0ad97ca',
    messagingSenderId: '86845493759',
    projectId: 'meninki-903d5',
    storageBucket: 'meninki-903d5.firebasestorage.app',
    iosBundleId: 'com.example.meninki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMorEvIYf8OfbdBCEqZqUVdpzHtua7lwM',
    appId: '1:86845493759:ios:4a8d2fd9f2728bf0ad97ca',
    messagingSenderId: '86845493759',
    projectId: 'meninki-903d5',
    storageBucket: 'meninki-903d5.firebasestorage.app',
    iosBundleId: 'com.example.meninki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwDbl8o7ZRowpiHNBG0WoIqevrciS37Os',
    appId: '1:86845493759:web:03086d2f398ac7f3ad97ca',
    messagingSenderId: '86845493759',
    projectId: 'meninki-903d5',
    authDomain: 'meninki-903d5.firebaseapp.com',
    storageBucket: 'meninki-903d5.firebasestorage.app',
    measurementId: 'G-S2PQJ0WTV0',
  );
}
